# TCL File Generated by Component Editor 18.1
# Thu Jan 11 12:46:02 CET 2024
# DO NOT MODIFY


# 
# DRS_Receiver_Interface "DRS-Receiver-Interface" v1.0
# MH 2024.01.11.12:46:02
# blah
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DRS_Receiver_Interface
# 
set_module_property DESCRIPTION blah
set_module_property NAME DRS_Receiver_Interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DRS
set_module_property AUTHOR MH
set_module_property DISPLAY_NAME DRS-Receiver-Interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ReceiverInterface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ReceiverInterface-e.vhd VHDL PATH ../../grpDrsReceiver/unitReceiverInterface/src/ReceiverInterface-e.vhd
add_fileset_file StrobeGen-Rtl-a.vhd VHDL PATH ../../grpStrobesClocks/unitStrobeGen/src/StrobeGen-Rtl-a.vhd
add_fileset_file StrobeGen-e.vhd VHDL PATH ../../grpStrobesClocks/unitStrobeGen/src/StrobeGen-e.vhd
add_fileset_file ReceiverInterface-Rtl-a.vhd VHDL PATH ../../grpDrsReceiver/unitReceiverInterface/src/ReceiverInterface-Rtl-a.vhd


# 
# parameters
# 
add_parameter gClkFrequency INTEGER 50000000
set_parameter_property gClkFrequency DEFAULT_VALUE 50000000
set_parameter_property gClkFrequency DISPLAY_NAME gClkFrequency
set_parameter_property gClkFrequency TYPE INTEGER
set_parameter_property gClkFrequency UNITS None
set_parameter_property gClkFrequency ALLOWED_RANGES -2147483648:2147483647
set_parameter_property gClkFrequency HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock csi_clk
set_interface_property s0 associatedReset rsi_reset_n
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitStates 1
set_interface_property s0 writeWaitTime 1
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 2
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point csi_clk
# 
add_interface csi_clk clock end
set_interface_property csi_clk clockRate 0
set_interface_property csi_clk ENABLED true
set_interface_property csi_clk EXPORT_OF ""
set_interface_property csi_clk PORT_NAME_MAP ""
set_interface_property csi_clk CMSIS_SVD_VARIABLES ""
set_interface_property csi_clk SVD_ADDRESS_GROUP ""

add_interface_port csi_clk csi_clk clk Input 1


# 
# connection point iByteDetected
# 
add_interface iByteDetected conduit end
set_interface_property iByteDetected associatedClock csi_clk
set_interface_property iByteDetected associatedReset rsi_reset_n
set_interface_property iByteDetected ENABLED true
set_interface_property iByteDetected EXPORT_OF ""
set_interface_property iByteDetected PORT_NAME_MAP ""
set_interface_property iByteDetected CMSIS_SVD_VARIABLES ""
set_interface_property iByteDetected SVD_ADDRESS_GROUP ""

add_interface_port iByteDetected iByteDetected ibytedetected Input 1


# 
# connection point rsi_reset_n
# 
add_interface rsi_reset_n reset end
set_interface_property rsi_reset_n associatedClock csi_clk
set_interface_property rsi_reset_n synchronousEdges DEASSERT
set_interface_property rsi_reset_n ENABLED true
set_interface_property rsi_reset_n EXPORT_OF ""
set_interface_property rsi_reset_n PORT_NAME_MAP ""
set_interface_property rsi_reset_n CMSIS_SVD_VARIABLES ""
set_interface_property rsi_reset_n SVD_ADDRESS_GROUP ""

add_interface_port rsi_reset_n rsi_reset_n reset Input 1


# 
# connection point oByteDetected_int
# 
add_interface oByteDetected_int interrupt end
set_interface_property oByteDetected_int associatedAddressablePoint ""
set_interface_property oByteDetected_int associatedClock csi_clk
set_interface_property oByteDetected_int associatedReset rsi_reset_n
set_interface_property oByteDetected_int bridgedReceiverOffset ""
set_interface_property oByteDetected_int bridgesToReceiver ""
set_interface_property oByteDetected_int ENABLED true
set_interface_property oByteDetected_int EXPORT_OF ""
set_interface_property oByteDetected_int PORT_NAME_MAP ""
set_interface_property oByteDetected_int CMSIS_SVD_VARIABLES ""
set_interface_property oByteDetected_int SVD_ADDRESS_GROUP ""

add_interface_port oByteDetected_int oByteDetected_int_irq irq Output 1


# 
# connection point oTimestampCounter
# 
add_interface oTimestampCounter conduit end
set_interface_property oTimestampCounter associatedClock csi_clk
set_interface_property oTimestampCounter associatedReset ""
set_interface_property oTimestampCounter ENABLED true
set_interface_property oTimestampCounter EXPORT_OF ""
set_interface_property oTimestampCounter PORT_NAME_MAP ""
set_interface_property oTimestampCounter CMSIS_SVD_VARIABLES ""
set_interface_property oTimestampCounter SVD_ADDRESS_GROUP ""

add_interface_port oTimestampCounter oTimestampCounter otimestampcounter Output 64


# 
# connection point oTimestampCapture
# 
add_interface oTimestampCapture conduit end
set_interface_property oTimestampCapture associatedClock csi_clk
set_interface_property oTimestampCapture associatedReset ""
set_interface_property oTimestampCapture ENABLED true
set_interface_property oTimestampCapture EXPORT_OF ""
set_interface_property oTimestampCapture PORT_NAME_MAP ""
set_interface_property oTimestampCapture CMSIS_SVD_VARIABLES ""
set_interface_property oTimestampCapture SVD_ADDRESS_GROUP ""

add_interface_port oTimestampCapture oTimestampCapture otimestampcapture Output 64

