# TCL File Generated by Component Editor 16.0
# Sun Dec 10 14:42:01 CET 2017
# DO NOT MODIFY


# 
# HexDigitController "7-Segment Hex Digit Controller" v1.0
# Michael Roland 2017.12.10.14:42:01
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module HexDigitController
# 
set_module_property DESCRIPTION ""
set_module_property NAME HexDigitController
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Michael Roland"
set_module_property DISPLAY_NAME "7-Segment Hex Digit Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL HexDigitController
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file HexDigitController.vhd VHDL PATH HexDigitController.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL HexDigitController
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file HexDigitController.vhd VHDL PATH HexDigitController.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL HexDigitController
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file HexDigitController.vhd VHDL PATH HexDigitController.vhd


# 
# parameters
# 
add_parameter INITIAL_OFF BOOLEAN true "Turn the 7-segment off on startup?"
set_parameter_property INITIAL_OFF DEFAULT_VALUE true
set_parameter_property INITIAL_OFF DISPLAY_NAME "Initially off?"
set_parameter_property INITIAL_OFF TYPE BOOLEAN
set_parameter_property INITIAL_OFF UNITS None
set_parameter_property INITIAL_OFF DESCRIPTION "Turn the 7-segment off on startup?"
set_parameter_property INITIAL_OFF HDL_PARAMETER true
add_parameter INITIAL_VALUE NATURAL 0 "Decimal value of the intially displayed hexadecimal digit"
set_parameter_property INITIAL_VALUE DEFAULT_VALUE 0
set_parameter_property INITIAL_VALUE DISPLAY_NAME "Initial value (decimal)"
set_parameter_property INITIAL_VALUE WIDTH ""
set_parameter_property INITIAL_VALUE TYPE NATURAL
set_parameter_property INITIAL_VALUE UNITS None
set_parameter_property INITIAL_VALUE ALLOWED_RANGES 0:2147483647
set_parameter_property INITIAL_VALUE DESCRIPTION "Decimal value of the intially displayed hexadecimal digit"
set_parameter_property INITIAL_VALUE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit seven_seg output Output 7


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 bridgedAddressOffset 0
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitStates 1
set_interface_property s1 writeWaitTime 1
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 s1_address address Input 1
add_interface_port s1 s1_read read Input 1
add_interface_port s1 s1_readdata readdata Output 32
add_interface_port s1 s1_write write Input 1
add_interface_port s1 s1_writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0

