#!/bin/bash

if [ -n "$BASH_SOURCE" ]; then
    THIS_SCRIPTX=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    THIS_SCRIPTX=$0
else
    THIS_SCRIPTX="$(pwd)/environmentinit"
fi

if [ -z "$ZSH_NAME" ] && [ "$0" = "$THIS_SCRIPTX" ]; then
    echo "Error: This script needs to be sourced. Please run as '. $THIS_SCRIPTX'"
    exit 1
fi

# set default build config and layers
export TEMPLATECONF="./layer/meta-application/conf/"

# $1 locate folder for oe build dir
source ./poky/oe-init-build-env $1

