# TCL File Generated by Component Editor 18.1
# Mon Jan 10 00:42:44 CET 2022
# DO NOT MODIFY


# 
# ModemChannelSelector "Modem Channel Selection Controller" v1.0
#  2022.01.10.00:42:44
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ModemChannelSelector
# 
set_module_property DESCRIPTION ""
set_module_property NAME ModemChannelSelector
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Modem Channel Selection Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ModemChannelSelector
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ModemChannelSelector.vhd VHDL PATH ModemChannelSelector.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ModemChannelSelector
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ModemChannelSelector.vhd VHDL PATH ModemChannelSelector.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL ModemChannelSelector
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ModemChannelSelector.vhd VHDL PATH ModemChannelSelector.vhd


# 
# parameters
# 
add_parameter CHANNEL_WIDTH NATURAL 4 "Number of bits of the channel index selection output signal"
set_parameter_property CHANNEL_WIDTH DEFAULT_VALUE 4
set_parameter_property CHANNEL_WIDTH DISPLAY_NAME "Channel index width (in bits)"
set_parameter_property CHANNEL_WIDTH TYPE NATURAL
set_parameter_property CHANNEL_WIDTH UNITS None
set_parameter_property CHANNEL_WIDTH ALLOWED_RANGES 0:4
set_parameter_property CHANNEL_WIDTH DESCRIPTION "Number of bits of the channel index selection output signal"
set_parameter_property CHANNEL_WIDTH HDL_PARAMETER true
add_parameter CHANNEL_DEFAULT NATURAL 0 "Default selected channel index"
set_parameter_property CHANNEL_DEFAULT DEFAULT_VALUE 0
set_parameter_property CHANNEL_DEFAULT DISPLAY_NAME "Default channel index"
set_parameter_property CHANNEL_DEFAULT TYPE NATURAL
set_parameter_property CHANNEL_DEFAULT UNITS None
set_parameter_property CHANNEL_DEFAULT ALLOWED_RANGES 0:16
set_parameter_property CHANNEL_DEFAULT DESCRIPTION "Default selected channel index"
set_parameter_property CHANNEL_DEFAULT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit channel output Output channel_width


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 bridgedAddressOffset 0
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitStates 1
set_interface_property s1 writeWaitTime 1
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 s1_address address Input 1
add_interface_port s1 s1_read read Input 1
add_interface_port s1 s1_readdata readdata Output 32
add_interface_port s1 s1_write write Input 1
add_interface_port s1 s1_writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0

